### ISSUE TITLE
ARM32 build

### ISSUE THREAD

**Issue by midzer** [Alex313031/Thorium-Special#1]
Hey,

just another idea. I've seen you released an ARM64 build. Awesome! :+1: 

Is ARM32 possible, too? I've seen many older mobile devices still use this.

Cheers
midzer

**Comment by Alex313031** [comment]
@midzer Your AVX build is up. And I'll be starting the ARM32 build soon.

**Comment by midzer** [comment]
I close this one for good as the ARM build has been published and is working for me, see https://github.com/Alex313031/Thorium-Special/releases/tag/M99.0.4761.0
