### ISSUE TITLE
sharing screen via Google Meet doesn't work on macOS arm64

### ISSUE THREAD

**Issue by altitudedashboard** [Alex313031/Thorium-Special#11]
Even if Screen Recording is granted via System Preferences.

**Comment by Alex313031** [comment]
I think this uses one of the apis in the api keys. Make sure you're added to > https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts as per > https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted

**Comment by pipashu** [comment]
@Alex313031 how to add api？

**Comment by pipashu** [comment]
Alex313031 Thank you for your reply. The problem is that I don't know how to add api key, so it seems I have to wait for the next version.

**Comment by Alex313031** [comment]
@pipashu Ok this version should work now

**Comment by Alex313031** [comment]
@pipashu Hows it coming. Latest Thorium MacOS release should work.
