### ISSUE TITLE
Unable to use fingerprint in bitwarden

### ISSUE THREAD

**Issue by toooonyy** [Alex313031/Thorium-Special#14]
Thorium | 105.0.5142.0 (Official Build) (arm64) macOS 12.4

Command Line | /Applications/Thorium.app/Contents/MacOS/Thorium --enable-features --disable-features=EventPath --flag-switches-begin --flag-switches-end

When I try to enable biometrics feature,

<img width="354" alt="Screen Shot 2022-06-30 at 11 18 14" src="https://user-images.githubusercontent.com/3480434/176640976-2d2b5bd0-e6bc-4386-b0b5-937ecbf49f8e.png">
 But I do have the desktop app installed and enabled.

Is this a Thorium's bug or Bitwarden limits this function as Thorium is a custom build?

**Comment by toooonyy** [comment]
> @toooonyy I don't think this is a Thorium bug. Can you get it to work in Chromium? There's this > https://bitwarden.com/help/biometrics/#:~:text=In%20your%20Bitwarden%20Desktop%20app,the%20Enable%20Browser%20Integration%20box.

I tried in ungoogled-chromium, works there but not Thorium

**Comment by Alex313031** [comment]
@toooonyy Nice. Gonna close this now.
