### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by vjrmy** [Alex313031/Thorium-Special#16]
maybe it can be made for android armv7, arm64 and x86
 With support extension like [Kiwi Browser](https://github.com/kiwibrowser/src.next)

**Comment by Alex313031** [comment]
@vjrmy I used to make android builds in Thorium Special. They were too much work, and I couldn't figure out the branding.

**Comment by XMA2l** [comment]
Also would appreciate an update.

**Comment by Alex313031** [comment]
@vjrmy @XMA2l I have started a new job at /e/OS foundation > https://e.foundation/e-os/ working on their browser. Because of this, and @nift4 [comment](https://github.com/Alex313031/Thorium-Special/issues/16#issuecomment-1183001665), I will be resuming work on Thorium Android releases! Stay tuned lol

**Comment by vjrmy** [comment]
OMG, congrats for your new job

**Comment by vjrmy** [comment]
I think in the future, thorium will be known to more people and maybe it will be like Brave Browser, good luck for your new path and I'm happy for you too

**Comment by Alex313031** [comment]
@vjrmy @nift4 @XMA2l @midzer I added commits to thorium repo for android builds, and am making a test arm64 build now. If it completes, I will upload here for yall to beta test.

**Comment by Alex313031** [comment]
@nift4 @vjrmy @XMA2l @midzer Here yall go > https://github.com/Alex313031/Thorium-Special/releases/tag/M107.0.5253.0-1

**Comment by vjrmy** [comment]
Sadly, my phone still in armeabi-v7a (Samsung M10) doesn't support arm64

**Comment by nift4** [comment]
App-Name & Icon are correct, but the intro says "Welcome to Chrome" and asks if I want to log-in to Google.

Discover spams "unable to render external view".

Default bookmarks contain Chromium Project references.

The about entry in Settings mention Google Chrome as well.

Many defaults send stuff to Google, like optional analytics. You should pick some Bromite patches.

Trying to run the BrowserBench JetStream2 resulted in tab death, though it probably just is my device being too weak. Kiwi Browser struggles with it too (the tab froze there).

**Comment by Alex313031** [comment]
@nift4 Thanks! I will work to correct the branding issues, and adding patches from Bromite.

I will probably leave chromium.org in the site suggestions, but remove the others and add thorium.rocks

**Comment by nift4** [comment]
Thorium definitefly is faster than other browsers I tried so far, even on my potato device. Good job!

**Comment by nift4** [comment]
FLOC is enabled by default on Android, please disable it.

The only thing on my wishlist is extension support otherwise but I'm aware thats a huge task and not easily doable.

**Comment by brnwlshubh** [comment]
@Alex313031 
Thorium Special is for Android build?
Or it will change in future?

**Comment by Alex313031** [comment]
@nift4 FLOC shouldn't be enabled? Can you send a screenshot or something? I don't have an android device right now but will be getting one soon.

**Comment by Alex313031** [comment]
@brnwlshubh Thorium Special is for builds that dont fit in the other repos. I use it for MacOS builds, and SSE4 builds, and now andorid builds. I might make a seperate repo for android.

**Comment by vjrmy** [comment]
> @nift4 FLOC shouldn't be enabled? Can you send a screenshot or something? I don't have an android device right now but will be getting one soon.

You may take a look to this link https://www.xda-developers.com/duckduckgo-brave-and-vivaldi-will-block-googles-floc/

**Comment by nift4** [comment]
> @nift4 FLOC shouldn't be enabled? Can you send a screenshot or something? I don't have an android device right now but will be getting one soon.

I correct myself, while "Privacy Sandbox trials" are enabled, FLoC is disabled and cannot be enabled. You should disable "Privacy Sandbox trials" by default as well though

**Comment by Alex313031** [comment]
@nift4 I'm actually in favor of the privacy sandbox, and so have not messed with it. I could make it off by default, but still enableable. Unlike FLOC, which I have forced to off.

**Comment by nift4** [comment]
Is there any difference between Privacy Sandbox and FLoC? I always thought Privacy Sandbox just was an settings category for FLoC. I would appreciate off-by-default.

**Comment by brnwlshubh** [comment]
> Sadly, my phone still in armeabi-v7a (Samsung M10) doesn't support arm64

Any update? @Alex313031

**Comment by Alex313031** [comment]
@nift4 No privacy sandbox is designed to *replace* FLOC. It takes care of some of its shortcomings. And @brnwlshubh we are actually making an arm32 build as I speak lol.

**Comment by vjrmy** [comment]
> @nift4 No privacy sandbox is designed to _replace_ FLOC. It takes care of some of its shortcomings. And @brnwlshubh we are actually making an arm32 build as I speak lol.

Don't forget to apply the extension support like kiwi browser or adblock engine like brave browser. Bromite have adblock using .dat files but it sucks

**Comment by Alex313031** [comment]
@vjrmy Adding extension support from kiwi is a __*big*__ task. Don't expect this super soon lol. As far as adblock, I might actually merge bromite and thorium. I.E. thorium for android would basically be bromite, but with the thorium patches on top of it, rather than just cherry picking individual patches from bromite.

**Comment by vjrmy** [comment]
@Alex313031 Alright, maybe the thing that can be achieved in the near future is to enter the privacyguides.org browser's recommendation

**Comment by Alex313031** [comment]
@nift4 @brnwlshubh @vjrmy @XMA2l Regular ARM (arm32) build is out, with some branding fixes, and systemwebview apk > https://github.com/Alex313031/Thorium-Special/releases/tag/M107.0.5279.0

**Comment by XMA2l** [comment]
This is awesome! I think if this will be taken serious, its own repo would be rlly handy! 
Also basing this on bromites patches sounds great! 
I have no idea how feasible this is as i didn't look into its code, but maybe putting mulch's vanadium picks on top could be nice? (Maybe not compatible/helpfull as they moved away from bromites patches? )
https://gitlab.com/divested-mobile/mulch
They claim those would be security related ... 

The arm64 build seems to run very nicely, an arm64 webview build would also be something i would definitely try out! 

Somehow inside website settings overview argumented reallity said it was turned off, but going into its settings its slider was on ...

**Comment by Alex313031** [comment]
@XMA2l Thorium actually already uses some patches from vanadium and bromite, as well as ungoogled chromium, brave, and iridium. I am thinking about basing the Android Releases on bromite, but without removing google search or google sync.

**Comment by Alex313031** [comment]
@nift4 @brnwlshubh @vjrmy @XMA2l Just made an android build for arm64 and arm32. Many fixes were made. Including the branding on the NTP.
