### ISSUE TITLE
Add feature Vertical Tabs

### ISSUE THREAD

**Issue by vjrmy** [Alex313031/Thorium-Special#17]
One feature that i love most in edge browser is vertical tabs. Can you make it this feature in thorium? especially for thorium SSE4

**Comment by Alex313031** [comment]
@vjrmy I wouldn't know how to do this. It would be a major rework of the browser, and thorium aims to not divert the UI from the chromium experience too much.

**Comment by Alex313031** [comment]
@vjrmy I will look more into it, but i still can't promise anything.
