### ISSUE TITLE
Raspberry pi 4 -  M105.0.5174.0 - Shared library problem

### ISSUE THREAD

**Issue by rbcet** [Alex313031/Thorium-Special#19]
Hello i have installed this package [thorium-browser-105.0.5174.0_arm64.deb](https://github.com/Alex313031/Thorium-Special/releases/download/M105.0.5174.0/thorium-browser-105.0.5174.0_arm64.deb)

with this command:
` sudo apt install ./thorium-browser-105.0.5174.0_arm64.deb `

I am trying to use this headless with npm puppeteer.

```
pi@raspberrypi:~ $ thorium-browser

/usr/bin/thorium-browser: error while loading shared libraries: libminigbm.so: cannot open shared object file: No such file or directory

pi@raspberrypi:~ $ uname -a

Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

pi@raspberrypi:~ $ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

**Comment by Alex313031** [comment]
@rbcet So you are running without GUI?

**Comment by ironyee** [comment]
@Alex313031 
I encountered the same problem. I'm running without GUI. 
How should I install it? Do you have any recommendations?

**Comment by Alex313031** [comment]
@ironyee @rbcet I think this commit will fix this, next build you guys can try it. > https://github.com/Alex313031/Thorium/commit/c0a8a68732baa4bbea4e0287ac55a85c142c7213

In the meantime, you can install libminigbm, or compile it yourself

**Comment by ironyee** [comment]
@Alex313031 
Thank you so much for the quick reply.
I'm going to wait for the next build.

**Comment by Alex313031** [comment]
@ironyee @rbcet Making new build now.

**Comment by ironyee** [comment]
@Alex313031 

Are you going to make a RPM package too?

**Comment by Alex313031** [comment]
I can try, Ive never made an rpm package of chromium or thorium before

**Comment by Alex313031** [comment]
@ironyee @rbcet New version should fix it, plus it has alot of new cool flags > https://github.com/Alex313031/Thorium-Special/releases/tag/M106.0.5215.0

Also @ironyee I answered your issue in the main repo.

**Comment by ironyee** [comment]
@Alex313031 Thank you, Alexander. You are the best.

**Comment by rbcet** [comment]
@Alex313031 thanks a lot, it works now
