### ISSUE TITLE
Worked Fine

### ISSUE THREAD

**Issue by chris-short** [Alex313031/Thorium-Special#2]
It's not signed by an Apple cert but aside from that, it worked great on an M1 Mac

**Comment by Alex313031** [comment]
@chris-short Nice! These mac builds for x64 and M1 are experimental. Realized I didn't update the main logo, so it still has the chromium logo. The mac builds are made by @midzer, and the next ones will have more compiler optimizations and correct logo. Thanks for trying Thorium!

**Comment by Alex313031** [comment]
Also, signing it would require a developer account and a full xcode installation. Midzer is compiling on his mac with just the xcode sdk, and without paying for a dev account. It actually IS signed, but not with an apple one or one in macos's trust store so.

**Comment by chris-short** [comment]
If y'all ever want someone to find that Apple Developer account, let me know.

**Comment by Alex313031** [comment]
@chris-short Ok will do. Well depending on where the macos builds go. Currently I mainly build for linux and win x64, but thorium-special has x64 and M1 mac builds, arm32 builds for raspi, and arm32/arm64 android builds, all of which are experimental. However going forward, I think Im gonna drop android builds and continue mac builds, and if they get to a level of polish Im comfortable with, I'll contact you here on what we can do to make some signed .app or .dmgs

**Comment by Alex313031** [comment]
@chris-short Hey, checking back in. The Mac releases have become regular now, so I'm checking back in on that offer for a dev account.
