### ISSUE TITLE
Extensions not detected in Thorium

### ISSUE THREAD

**Issue by leomc1118** [Alex313031/Thorium-Special#20]
When I go to "chrome://extensions/" after updating to a new version of Thorium, the extensions that carry over don't show up. Am I doing something wrong with the update process? I'm on Mac M1 Version 106.0.5212.0 (Official Build) (arm64)

**Comment by Alex313031** [comment]
@leomc1118 This has been fixed, but the Mac builds need to be updated, the latest ones are from before the commit that fixed it. We are making mac releases tomorrow so just wait until then.

**Comment by leomc1118** [comment]
Thank you! Keep up the good work

**Comment by Alex313031** [comment]
@leomc1118 new releases > https://github.com/Alex313031/Thorium-Special/releases/tag/M107.0.5253.0
