### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Special#22]
Hello, i see with great pleasure that Thorium make android version ! tahnk you very much !

we hope Thorium android support extensions like open source kiwi browser or iceraven browser, and even support extensions from miceosoft edge browser because sometimes we need to download youtube videos, video extensions in chrome store are not allaowed to download from youtube however in edge store, we can do it via videodonwload helper extension , and may be Thorium an droidn can even install extensions from firefox addons store because they use the same web extension api.....

thank you very much :)

**Comment by Alex313031** [comment]
@trimechee I would also like to add extension support. It is a big task. I might be able to use Kiwi browser's work for this.

**Comment by trimechee** [comment]
Great ! Thank you very much :) Kiwi seems to have some ads in home page, some peple says there is no ads in github version of kiwi, in any case we hope Thorium will have no ads

**Comment by trimechee** [comment]
@Alex313031 We hope that you will fork iceraven browser as is the case for mercury browser, the interest is that fireox android only adds some extensions, iceraven android adds more extensions but not all extensions, so we hope that you will make a version of firefox android to add all the extensions and addon of desktop browser for exemple add extension to  stretch video upscale video in streaming sites, thank you :)

https://github.com/fork-maintainers/iceraven-browser


I noticed that when I disabled media source extension MSE, some video players work but some video players don't work in streaming sites, so I hope Thorium will find a solution to buffer at least 60 seconds of media content to avoid the jerks interruption of video playback, I have read documentation and web browsers seem to miscalculate the network internet speed which can vary for example when people connect to wifi so the strong connection becomes weak and they do not buffer media sufficiently , this is the biggest flaw of browsers, even in rich countries there are remote places villages with weak connection, they are sometimes deprived of video :)

**Comment by Alex313031** [comment]
@trimechee Interesting, I will loko into iceraven

**Comment by trimechee** [comment]
Wonderful ! thank you very much !
