### ISSUE TITLE
[Question] about some useful patches

### ISSUE THREAD

**Issue by chromer030** [Alex313031/Thorium-Special#23]
Hey, thank you very much for this great and useful project.
The question is : Are the patches like :

- All Codecs (h264, h265, flac, xvid, AV1, etc..)
- Hardware Acceleration Video Decode
- Widevine
- PlatformHEVCDecoderSupport
- ThinLTO, PGO
- X/Wayland (vaapi)
- etc

which are included in builds like [macchrome](https://github.com/macchrome?tab=repositories) ones , included in Thorium builds or is it possible to include them at all ?

**Comment by Alex313031** [comment]
@chromer030 Thorium has all of these, and more. See https://github.com/Alex313031/Thorium/blob/main/infra/PATCHES.md and  https://thorium.rocks/optimizations.html

The HEVC seems to be broken on the linux releases for now though, but I am working on it.

**Comment by chromer030** [comment]
Excellent , thanks for your efforts.
