### ISSUE TITLE
FireDM (old name "pyidm")

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Special#29]
Hello, i discover that Mr @Alex313031 not only develop Thorium brower and Thorium os but also develop several other awesome projects, it's awesome and thank you so much!

Sorry I don't know where to post my request, there was a famous software, several sites and users praised it like the ghacks site, this software is a powerful donwloader with a lot of magnificent unique options based on yr-dlp aevc a specific download accelerator more faster than ariac2c....but this open source project mysteriously disappears in April and the last version of April disables the software so we had to stay with the penultimate version....

fortunately some people have saved a copy of this software but its development has unfortunately stopped and no one seems to have restarted the project, I wonder if Mr. Alex can resume the project by forking it especially since it's based on yt-dlp and the software is very mature and complete and why not change the name of the downloader to Thorium Downloader manager since this project is abandoned and you are doing a favor by trying to relaunch the project ..... 

I looked for an alternative and I found the magnificent "Media-Downloader" on github but it pains me to see that this firedm project has been abandoned and we hope that it will be relaunched on windows and linux......thanks a lot !

https://github.com/afzl-wtu/firedm

https://www.ghacks.net/2020/08/13/pyidm-is-an-open-source-download-manager-that-can-download-videos-and-playlists/

**Comment by Alex313031** [comment]
@trimechee Let me look into it and see.

**Comment by trimechee** [comment]
Awesome !! Thank you so much !🥇
