### ISSUE TITLE
Tab font colour

### ISSUE THREAD

**Issue by Martin1134** [Alex313031/Thorium-Special#3]
Hi :) 

Browser works great, but is there a way to change from the original red tab font colour? :D 

Edit: Widevine seems to be not working.

**Comment by n006** [comment]
It should be mentioned that using themes does not solve the issue.
It seems to have some overruling settings which I could not find yet.

**Comment by Martin1134** [comment]
In Chromium, the colors are just as expected 👀

![image](https://user-images.githubusercontent.com/44879342/158419781-d737ac64-8111-414b-ba5e-d95625e96ca3.jpeg)

**Comment by kapoorlakshya** [comment]
> I rely on a friend to compile the Mac releases as I do not own a Mac.

@Alex313031 I'm moving over to Thorium from SRWare Iron and hoping to use this long term. Happy to help with compiling for mac releases on a M1.

**Comment by Alex313031** [comment]
@n006 @Martin1134 What Chromium version are you using, and are you using a vanilla snapshot from google, or someone elses chromium i.e. from chromium.woolyss.com?

@kapoorlakshya THAT would be a big help. I am friends with @midzer and talked with him on twitter and guided him from start to finish on compiling Thorium. 
This repo only holds build.gn files for various architectures. The main repo hosts all the main source code, but the instructions are only for linux, with some small comments about windows.
Where would you like to talk so we can chat about thorium, and/or so I can tell you how to build it.
I've got pretty much everything. FB, instagram, twitter, reddit, tumblr, discord, etc.

**Comment by n006** [comment]
@Alex313031 I was using woolyss chromium versions for years until I switched to M1. For a few months now Thorium is the first binary to work on my machine. Can't remember which was the last woolyss version working for me.

**Comment by Alex313031** [comment]
@kapoorlakshya @n006 @Martin1134 New Max builds are out, courtesy of @midzer 
https://github.com/Alex313031/Thorium-Special/releases/tag/M102.0.4952.0-1

**Comment by Martin1134** [comment]
Everything working now 😬

<img width="1440" alt="Screenshot 2022-03-20 at 07 37 18" src="https://user-images.githubusercontent.com/44879342/159151246-f158f0d9-6556-4fab-b7a1-3ddd562610d3.png">

**Comment by n006** [comment]
Great. Trank you.

**Comment by Alex313031** [comment]
@Martin1134 You should uninstall thorium, clear the icon cache, then reinstall, because I see the old thorium logo/shortcut is still there.

**Comment by kapoorlakshya** [comment]
@Alex313031 Thanks for the build requirements and the new release! I have a M1 Max w/ 64 GB so curious to see how long it takes on that.

I feel like I'm obligated to say let's sync on [Reddit Chat](https://www.reddit.com/chat/) since I work there haha, but Discord works as well.

**Comment by kapoorlakshya** [comment]
> @kapoorlakshya okay! Whats your reddit /u/? And with that hardware it might take two hours or less.

u/kapoorlakshya

**Comment by Alex313031** [comment]
@kapoorlakshya Ok I sent a chat request.
