### ISSUE TITLE
Biometric Authentication Apple Silicon

### ISSUE THREAD

**Issue by gotschi** [Alex313031/Thorium-Special#31]
Hello thank you for the Apple builds first off! :)

Do you think it is possible to add Biometric Authentication to Thorium? 
As far as I can see Chromium should have this already or am I missing something here?

**Authn** works really well in Safari with the Fingerprint sensor and I also have Bitwarden inside Thorium use the Fingerprint reader already fine.

What is needed for this?

thanks!

edit:
this is available currently:

<img width="450" alt="Bildschirm­foto 2022-11-08 um 10 27 23" src="https://user-images.githubusercontent.com/213873/200527877-b645d06e-05ee-4bb4-8686-f7e2d1ba5def.png">

**Comment by Alex313031** [comment]
@gotschi Can you see if the latest M111 version has this functionality?

**Comment by gotschi** [comment]
The popup selection still only gives

- USB Security Key
- A different device (qr code)

whereas safari prompts straight to scan the fingerprint

**Comment by mietzen** [comment]
Sorry for stealing your Issue, but this might be related.

> Bitwarden inside Thorium use the Fingerprint reader already fine.

How did you manage to do this? I always get this message:
![image](https://user-images.githubusercontent.com/31704359/229341726-ddacfe3f-4a6e-4593-9bfe-7484a86ae081.png)

Firefox and Safari are working fine.

Thorium: Version 111.0.5563.69 (Official Build) (arm64)
MacOS: 13.2.1 (22D68) (M1 Pro)

**Comment by gotschi** [comment]
> > Bitwarden inside Thorium use the Fingerprint reader already fine.
> 
> How did you manage to do this?

you need to copy over the `NativeMessagingHosts` File from chromium / chrome to Thoriums userfolder as the Bitwarden Desktop app does not know about this browser
