### ISSUE TITLE
Thorium for older intel MacOS

### ISSUE THREAD

**Issue by panabike** [Alex313031/Thorium-Special#33]
For stupid reasons I need to keep my old 2007 iMac running. Unfortunately there isn't a modern, secure browser available. Every one I've tried including Thorium complain they're not compatible with Mac OS El Capitan 10.11.6 which is  the most modern MacOS that runs on this old lady.

Currently I'm running old unsupported Safari and Firefox. Old Chrome based browsers won't even load.

Any hope for Thorium to become retro?

**Comment by Jazzzny** [comment]
Not directly related to Thorium, but the Chromium-Legacy Project backports up-to-date Chromium to Mac OS X 10.7-macOS 10.12: https://github.com/blueboxd/chromium-legacy

**Comment by Alex313031** [comment]
@panabike @Jazzzny Yeah, this is not something I'm gonna do because it requires extensive reworking of Chromium. I would try what @Jazzzny said if you wanna run chromium on old macos versions.
