### ISSUE TITLE
New updates

### ISSUE THREAD

**Issue by petar-staynov** [Alex313031/Thorium-Special#34]
Hey, 
Are there any plans releasing a new version of this browser?
The MacOS builds have some issues with certain websites and Google Sheets and are a few months old.

**Comment by joeshae** [comment]
+1

**Comment by TzunamiOSX** [comment]
Yes, a new release would be nice.

**Comment by Alex313031** [comment]
@petar-staynov @joeshae @TzunamiOSX New MacOS and SSE3 versions are out.

**Comment by csrutil** [comment]
@Alex313031 Thank you so much!
