### ISSUE TITLE
KeepassXC extension not working on Thorium?

### ISSUE THREAD

**Issue by sergiocasero** [Alex313031/Thorium-Special#36]
Hi folks! Just trying to use KeePass with Thorium with no luck, I always get:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/10833202/216837847-637d7d7e-5a53-49ce-8088-2189343a8bac.png">

I've tested on chrome and chromium and it works as expected. I've also removed all the keys in keepass (because maybe there were conflicts or something) but no luck, it doesn't work.

**Comment by sergiocasero** [comment]
@gz83 keepassXC.

**Comment by sergiocasero** [comment]
@gz83 finally found the solution!!

I'll post here if anyone needs this in the future:

The problem is that Thorium and Chromium are "the same browser" so keepass is detecting the NativeMessagingHosts for chromium, so in Browser integration -> Advanced we need to override the location of the proxy.

Enable "use custom proxy", select browser type: "Chrome", and for the location, put this
`/Users/sergio/Library/Application Support/Thorium/NativeMessagingHosts`

instead of
`/Users/sergio/Library/Application Support/Chromium/NativeMessagingHosts`

And that's it!

**Comment by devgizzo** [comment]
On MacOS the /Users/youruser/Library/Application Support/Thorium/NativeMessagingHosts folder is empty if you install it next to some other chromium browser, copying the json file over to this folder solves the issue.

**Comment by aldobelus0** [comment]
I adapted to GNU/Linux the solution exposed further up and has given result. The path in my operating system is 

### `/home/usuario/.config/thorium/NativeMessagingHosts`

Now, you only have to substitute the explained before to this place and you got it. 

At first, it has occurred to me that the extension didn't adopted the change. I had to uninstall everything, to include the modification in the browsers integration of the application (next image) and to install again the extension. Then yes, it has produced  the change.

![CAPTURA-GITHUB2](https://github.com/Alex313031/Thorium-SSE3/assets/15985449/df56f38c-22d7-44a0-89e2-3c483049c5cb)

Good Luck!

---

**NOTE**: Don't be surprised when you discover that there is not archive in the route to NativeMessagingHosts. It will create itself automatically when the extension loads.

![CAPTURA-GITHUB3](https://github.com/Alex313031/Thorium-SSE3/assets/15985449/5a7cb6cb-bb60-4817-b14c-dab885528bea)

**ANOTHER NOTE**: I left this area like that (next image). Chromium only.  It wasn't needed to check Google Chrome too. 

![CAPTURA-GITHUB4](https://github.com/Alex313031/Thorium-SSE3/assets/15985449/1d5262a6-79ad-485b-930d-8c631251e986)

If you find any problem ask for more information. I have doubts about my explanations... xD
