### ISSUE TITLE
new SSE3/SSE4 linux build

### ISSUE THREAD

**Issue by lavilao** [Alex313031/Thorium-Special#38]
Hi, first of all thanks for your work, could you update the linux build? Also, can I build this in github actions? Thanks in advice!

**Comment by lavilao** [comment]
after some research finded that chromium cant be builded in github actions, requires too much space xD

**Comment by Alex313031** [comment]
@gz83 @lavilao Yes and the space, RAM, and CPU horsepower required is not available on the free tier. We would have to pay for a CI license. Don't worry though @lavilao I will be making an SSE3 build soon for those of us with older CPUs (I use the sse3 releases on a Core 2 Duo system of mine)

**Comment by lavilao** [comment]
@Alex313031 Thanks! is good to see us dual core users are not forgotten xD.

**Comment by Alex313031** [comment]
@lavilao Here you go > https://github.com/Alex313031/Thorium-Special/releases/tag/M110.0.5481.179-1

**Comment by lavilao** [comment]
@Alex313031 Thank you!

**Comment by lavilao** [comment]
it does not open 🥲, it crashes with ```illegal hardware instruction (core dumped)  thorium-browser```
