### ISSUE TITLE
SSE3 windows build opens but immediately closes

### ISSUE THREAD

**Issue by JaegerFox** [Alex313031/Thorium-Special#43]
in the latest M110.0.5481.179-2 thromium displays a blank window and immediately closes without any error message.
OS: Windows 8.1 x64

**Comment by Alex313031** [comment]
@JaegerFox Chromium ended support for Windows 7/8/8.1 with version 110. I have made a special site just for win7, and the builds in there will also work with 8 and 8.1 > https://thorium.rocks/win7
