### ISSUE TITLE
Question: Coloured Bar in Add Tab to New Group?

### ISSUE THREAD

**Issue by aaykut** [Alex313031/Thorium-Special#44]
Hi,

Quick question:

I'm on 110.0.5481.178 (Official Build) (arm64)

I see that there is a coloured "bar" next to the Add Tab to New Group option.

![image](https://user-images.githubusercontent.com/5464592/226993230-3f6eb068-280b-4c12-9425-c38a907b5f7a.png)

Is this new? I don't see it in Chrome. Can it be disabled?

Thanks,
Anthony

**Comment by Alex313031** [comment]
@aaykut This is supposed to say "New". It is an issue on MacOS.

**Comment by Alex313031** [comment]
@aaykut "Fixed" simply because I removed it since tab groups is not new anymore.
