### ISSUE TITLE
Doesn't display certain videos

### ISSUE THREAD

**Issue by ftphikari** [Alex313031/Thorium-Special#45]
OS: macOS Mojave 10.14.6 (18G9323)
Thorium: 110.0.5481.178 (Official Build) (x86_64)

H265 videos work in Thorium, but not in Google Chrome - good.
But this video works in Chrome, but not in Thorium: https://developer.apple.com/videos/play/wwdc2021/10161

Why? Bug?

**Comment by gz83** [comment]
> OS: macOS Mojave 10.14.6 (18G9323) Thorium: 110.0.5481.178 (Official Build) (x86_64)
> 
> H265 videos work in Thorium, but not in Google Chrome - good. But this video works in Chrome, but not in Thorium: https://developer.apple.com/videos/play/wwdc2021/10161
> 
> Why? Bug?

@ftphikari 

I tested on the windows version and found that the video can be watched normally, please try to see if you can watch the video in incognito mode.

**Comment by ftphikari** [comment]
No, it does not work in incognito mode either. In case you need more detail - sound works, subtitles are shown, just the video itself is black.

**Comment by midzer** [comment]
I can't confirm this bug using same version on Mac M1.

Maybe some1 else with the x64 version has this issue, too
