### ISSUE TITLE
Thorium 109 special Windows SSE4.2 build for Windows 7

### ISSUE THREAD

**Issue by pritkr** [Alex313031/Thorium-Special#47]
![image](https://user-images.githubusercontent.com/81620727/230911114-19b2ec23-dffa-48f2-88ea-c19d004de940.png)
I have a Windows 7 system with a CPU that supports SSE4.2 and AVX. However, when I try to launch Thorium 109 AVX builds, it immediately crashes.
Therefore, I am requesting a special Windows SSE4.2 build (this [build ](https://github.com/Alex313031/Thorium-Special/releases/tag/M105.0.5115.0)works for me)of Thorium 109 that will work for Windows 7 users, including myself.
I understand that this may be an edge case, but I believe this is the only more version needed for Windows 7 users.
I apologize for any inconvenience caused, and I would not have made this request if I had the necessary resources to build it myself.
Thank you.

**Comment by gz83** [comment]
> ![image](https://user-images.githubusercontent.com/81620727/230911114-19b2ec23-dffa-48f2-88ea-c19d004de940.png) I have a Windows 7 system with a CPU that supports SSE4.2 and AVX. However, when I try to launch Thorium 109 AVX builds, it immediately crashes. Therefore, I am requesting a special Windows SSE4.2 build (this [build ](https://github.com/Alex313031/Thorium-Special/releases/tag/M105.0.5115.0)works for me)of Thorium 109 that will work for Windows 7 users, including myself. I understand that this may be an edge case, but I believe this is the only more version needed for Windows 7 users. I apologize for any inconvenience caused, and I would not have made this request if I had the necessary resources to build it myself. Thank you.

@pritkr 

Please use the following version:
https://github.com/Alex313031/Thorium-Special/releases/tag/M109.0.5414.120-1

**Comment by gz83** [comment]
> > > ![image](https://user-images.githubusercontent.com/81620727/230911114-19b2ec23-dffa-48f2-88ea-c19d004de940.png) I have a Windows 7 system with a CPU that supports SSE4.2 and AVX. However, when I try to launch Thorium 109 AVX builds, it immediately crashes. Therefore, I am requesting a special Windows SSE4.2 build (this [build ](https://github.com/Alex313031/Thorium-Special/releases/tag/M105.0.5115.0)works for me)of Thorium 109 that will work for Windows 7 users, including myself. I understand that this may be an edge case, but I believe this is the only more version needed for Windows 7 users. I apologize for any inconvenience caused, and I would not have made this request if I had the necessary resources to build it myself. Thank you.
> > 
> > 
> > @pritkr
> > Please use the following version: https://github.com/Alex313031/Thorium-Special/releases/tag/M109.0.5414.120-1
> 
> I already use the SSE3 version can a SSE4.2 version be made for windows 7 users?

The SSE3 version is also fine for now. Regarding the problem you are experiencing, please try running the browser with clean user data and see if it crashes again.
