### ISSUE TITLE
Virus on Thorium 109.0.5414.120_SSE2_x86 mini_installer (2023-01-30).exe

### ISSUE THREAD

**Issue by Cixert** [Alex313031/Thorium-Special#51]
Analysis
-----------
Avast & AVG = Win32: Malware-gen
F.Secure = Trojan.TR/Crypt.ZPACK.Gen2
Trapmine = Malicious.high.ml.score

**Comment by Cixert** [comment]
Download link virus version
https://github.com/Alex313031/Thorium-Special/releases/tag/M109.0.5414.120-1

**Comment by gz83** [comment]
@Cixert 

None of the three antivirus programs WD && Kaspersky && ESET reported this file as a virus, if it is reported as a virus, it may be a false alarm

**Comment by Cixert** [comment]
> @Cixert
> 
> None of the three antivirus programs WD && Kaspersky && ESET reported this file as a virus, if it is reported as a virus, it may be a false alarm

You can try to upload the file to virustotal.com
(online link does not perform tests with the antivirus described)
And yes, only those detect it.
Other Thorium versions are not detected.

**Comment by Alex313031** [comment]
@Cixert I can assure you that no software that I create or commit to has any malware in it whatsoever. This is strange.

I don't sign any of the thorium installers, and sometimes when downloading a browser will warn about it, but I've never seen it come up as flagged by an antivirus.

You can view the source code in the main repo. If you don't trust it, you could build it yourself, and then compare the hashes to what I publish, and see that they are indeed the same.

Also, I'm assuming you are using this release for windows 7 or 8, in which case I made a seperate repo with more up to date builds with backported patches here > https://github.com/Alex313031/thorium-win7
