### ISSUE TITLE
Google search engine ui bug

### ISSUE THREAD

**Issue by stchristian** [Alex313031/Thorium-Special#6]
I've just installed this latest build for arm64 mac

[M103.0.5020.0](https://github.com/Alex313031/Thorium-Special/releases/tag/M103.0.5020.0-1)

Spotted a slight UI bug on the google search page

<img width="675" alt="image" src="https://user-images.githubusercontent.com/24798850/166314238-eca3629a-ea01-4808-b4e5-914829d856db.png">

I tried to find the code where this page is implemented, but couldn't. Otherwise I would have opened a PR :-)

Also just an idea, it may be easier and more maintainable to have like 1 page for all search engines. Like firefox does

<img width="986" alt="image" src="https://user-images.githubusercontent.com/24798850/166314637-4c31f500-6a8c-455d-a0c9-a9c538da591e.png">

**Comment by Alex313031** [comment]
@stchristian I am aware of this bug. It affects all platforms, and Im pretty sure it's an upstream chromium bug.

And Thorium doesn't attempt to change the UI in major ways (although it does have experimental features enabled, and has a new menu on the reload button that can be accessed by right clicking on it), so although I do find that feature useful in firefox, it is probably not something I will implement in Thorium, assuming I could even figure out how to do so.
