### ISSUE TITLE
Widevine arm64

### ISSUE THREAD

**Issue by Shell3** [Alex313031/Thorium-Special#60]
**System Details**
 - OS: Debian 11
 - Thorium Version 114.0.5735.134

**Problem**
Cannot get widevine drm working.

**Additional Notes**
I tested using [Bitmovin](https://bitmovin.com/demos/drm) and the Spotify web playback SDK. I'm trying to get Thorium working with widevine on other arm64 boards (OrangePi, Radxa). I tested Thorium also on RPI 4 64bit where it seems to be non-functional as well, in the native chromium app for RPI 4 64bit the widevine is functional.

**Comment by Alex313031** [comment]
@Shell3 I will test on my new Pi coming in the mail and get back to you.

**Comment by akancz** [comment]
@Alex313031 The DRM widevine feature is only supported on RPi4 board ? Or can it be used on other ARM64 boards (OrangePi, Radxa, ...) ?

**Comment by Alex313031** [comment]
@Shell3 @akancz This commit > https://github.com/Alex313031/thorium/commit/f2c295f3b6c2a582c345814c72dac9216c4827eb should hopefully get widevine working on linux on the Pi 4

**Comment by Shell3** [comment]
@Alex313031 Are you able to provide a build with it, please?
