### ISSUE TITLE
Extension support

### ISSUE THREAD

**Issue by Degl1** [Alex313031/Thorium-Special#61]
I would like to have extension support when using Thorium on my Android.

Said patches can be found at: https://github.com/dvalter/chromium_extension_patches . I would love to use Thorium but I want to use extensions on my phone.

**Comment by gz83** [comment]
Thank you for the information, but since the patch was made 3 years ago and multiple versions have passed since then, plus the patch is relatively huge, if it needs to be used on the current version, it will require a lot of code changes and I will discuss it further with Alex.

@Alex313031

**Comment by daBroma** [comment]
Fair enough, but the patch seems to work fine for Kiwi Browser AFAIK since the v112 build supports extensions still unless the updated patch is closed source.
