### ISSUE TITLE
Open Magnet Links

### ISSUE THREAD

**Issue by BigT2013** [Alex313031/Thorium-Special#69]
Is there a way to enable Thorium to open Magnet links. I've tried many different things, but no go... Please advise, thank you for your help.

I'm downloading with an external app, but Thorium does not ask to send Magnet links to app. Please update.

**Comment by gz83** [comment]
Do you want to download files from magnet links? If so, I think it would be better to leave this job to a third-party downloader.

**Comment by Alex313031** [comment]
@BigT2013 Thorium can't open magnet links because it is not a Bittorrent client.

If you mean automatically opening the bittorrent client when one clicks on a magnet link, it should happen automatically.
Make sure that Bittorrent or qBittorrent has been installed with proper file type handling for .torrent and .magnet files.

Lastly, you could check at chrome://settings/handlers and see what it says.

**Comment by RealFakeGitter** [comment]
Hi, Want to add that i have this issue and further explain my own situation, if you want me to open a new issue advise.

I am using thorium on Gauruda Linux.
I previously used it on windows and the windows version did not have this issue. 

On garuda Linux however, When i click on a magnet link I do not get all my torrent clients (specifically Qbitorrent) as an option to open. (Or anything other then Orion which is only a torrent streaming option) See Here:

![image](https://github.com/user-attachments/assets/c75b9810-ff43-4a0c-9d36-1a6b9ffe481e)


this option DOES come up on firefox, so its not a issue with the qbitorrent configuration but thorium. 

![image](https://github.com/user-attachments/assets/6509afc3-0e6c-42e8-ab21-b79199d52fee)



Furthermore , when i go to chrome://settings/handlers i do not see any option in thorium at all to handel magnet links, or for that matter anything , here is what I See :

![image](https://github.com/user-attachments/assets/d7758ebb-2f51-4007-9e34-96e36bc1b5b5)

If I am missing something here please let me know. 

The version of Thorium I am on is :
Version 126.0.6478.231 (Official Build) stable, built on Ubuntu (SSE3) (64-bit)


Quick edit. I was able to get Qbitorrent to show by running :
xdg-mime default org.qbittorrent.qBittorrent.desktop x-scheme-handler/magnet

BUT

I can not have all my clients show as it shows in Firefox and let me select which one i would like to use
