### ISSUE TITLE
Windows on ARM build

### ISSUE THREAD

**Issue by alexandreteles** [Alex313031/Thorium-Special#7]
Hello,

Would it be possible for you to produce a Windows build for ARM64, maybe targeting ARMv8-A/Cortex-A76 with NEON extensions enable?

**Comment by Alex313031** [comment]
@alexandreteles Are you going to be running it on a raspi? Because I actually already have it march and mtuned to armv8-a and cortex-a76 respectively with neon extensions. I wouldn't have to change anything in source, just compile it for Win arm64

**Comment by alexandreteles** [comment]
@Alex313031 I'll be running it on a couple Galaxy Book Go laptops, they're equipped with the Snapdragon 7c Gen 2 processor and Windows 11!

**Comment by Alex313031** [comment]
@Okay, I will make a build for you soon.

**Comment by Alex313031** [comment]
@alexandreteles We are making an arm64 build today as well as an sse4 build for older processors.

**Comment by Alex313031** [comment]
@alexandreteles Unfortunately, we are having issues cross building for windows on arm.

**Comment by alexandreteles** [comment]
Oh, that's sad. Could you share the build files so I can try locally on my Windows installation running on x64?

**Comment by Alex313031** [comment]
@alexandreteles You can compile it yourself.You will need 60+GB of space, 8GB RAM, and the more powerful the cpu, the better. Preferably with at least 4 cores. I've written instructions in the repo for building for linux and windows, and cross building for windows

**Comment by Alex313031** [comment]
@alexandreteles We got a working build! Although we had to disable -O3, which is one of the things that gives Thorium its performance, but it should still be faster than a vanilla chromium/chrome build. We also really need someone to test it, to make sure it works. Would you be willing to do that.

**Comment by alexandreteles** [comment]
Sure, I'll test it and get back to you in one or two days. Thank you very much for the build!

**Comment by Alex313031** [comment]
@alexandreteles Hows it comin?

**Comment by alexandreteles** [comment]
Okay, it seems to be working just fine for me. It isn't faster than Edge but it's clean. I'll start deploying it to the machines and update you during the process.

**Comment by Alex313031** [comment]
@alexandreteles I have been doing some work with the main BUILD.gn, and @gz83 we should try to use the new artifacts (or maybe native build since we will be doing that anyway). New Win On ARM build should come soon,

**Comment by braddarwin** [comment]
I'll kick the tires on my surface pro x with it too.

**Comment by Alex313031** [comment]
@alexandreteles  @da-brad New build coming soon

**Comment by da-brad** [comment]
> @alexandreteles @da-brad New build coming soon

new ARM build still in process?

**Comment by alexandreteles** [comment]
Took me longer than expected to come back to you because, I'll be honest, I forgor 💀 But anyway, it works better than the Chrome build for Windows on ARM. Deployment was a breeze after wrapping it on a MSI file, but I do feel that without the optimizations some performance is left on the table.

I'm waiting for the new builds, thank you for your time!

**Comment by Alex313031** [comment]
@da-brad @alexandreteles Yeah, we were having some issues. We should be making an arm build in the coming week.

And how did you wrap it in an msi file? Besides, why are you doing that, is the .exe not enough? If the reason is you are trying to install it system wide rather than per user, there is a cmdline flag for that.

**Comment by alexandreteles** [comment]
> @da-brad how did you wrap it in an msi file? 

Using [WiX](https://wixtoolset.org/)

> Besides, why are you doing that, is the .exe not enough?

Literally because of company policy.

**Comment by Alex313031** [comment]
@alexandreteles Interesting.

**Comment by da-brad** [comment]
I'm excited to give it a shot @Alex313031 and @alexandreteles.  And when I do, I'll look to use the exe file whenever the newest release is available.  Thank you!

**Comment by alexandreteles** [comment]
@Alex313031 and @gz83 Are we ever getting an updated version for Windows on ARM? On the latest Win11 update it stopped working for me with error code `STATUS_BREAKPOINT`. I'm always over here to test new builds :)

**Comment by Alex313031** [comment]
@da-brad @alexandreteles Me and @gz83 are working on a new Windows on ARM build.

**Comment by Alex313031** [comment]
@da-brad @alexandreteles @gz83 At long last, we FINALLY have a fully working, bug free (unless there is something I didn't catch in my extensive testing) Windows on ARM64 build. I tested with Windows 10 and Windows 11 on a Raspberry Pi 4.

Here ya'll go. It should work on any device running Windows for ARM, except for Windows RT (Based on Windows 8.1, used on the original surface, because 1. that device is ARM32, and 2. Chromium dropped support for Win7/8/8.1 with M109)

https://github.com/Alex313031/Thorium-Special/releases/tag/M115.0.5790.172-2

**Comment by alexandreteles** [comment]
I will get to test it as soon as I have some free time!

**Comment by Alex313031** [comment]
@alexandreteles @da-brad I can't test right now, so can one of you test the latest M119 win on arm build?

**Comment by alexandreteles** [comment]
I could, but it would take a couple days.

**Comment by Alex313031** [comment]
@alexandreteles I was able to test, and it is broken, but luckily I know how to fix it, I just need to rebuild natively on a real Windows machien.
