### ISSUE TITLE
Help with building on M1 Mac

### ISSUE THREAD

**Issue by wscullen** [Alex313031/Thorium-Special#9]
Hi! Thank you for the hard work and creating M1 builds for chromium, it is very appreciated. I was hoping to build the latest version of chromium (although there has been a new release since I started trying to build myself), but I can't get past the gn args generation step:

```
 ~/chromium/src/> gn args out/thorium
Waiting for editor on "/Users/<useraccount>/chromium/src/out/thorium/args.gn"...
Generating files...
ERROR Unresolved dependencies.
//:blink_web_tests_support_data(//build/toolchain/mac:clang_arm64)
  needs //content/shell:thorium_shell(//build/toolchain/mac:clang_arm64)
//:chromium_builder_asan(//build/toolchain/mac:clang_arm64)
  needs //content/shell:thorium_shell(//build/toolchain/mac:clang_arm64)
//:gn_all(//build/toolchain/mac:clang_arm64)
  needs //content/shell:thorium_shell(//build/toolchain/mac:clang_arm64)
//content/shell:content_shell_crash_test(//build/toolchain/mac:clang_arm64)
  needs //content/shell:thorium_shell(//build/toolchain/mac:clang_arm64)
//content/test:content_browsertests(//build/toolchain/mac:clang_arm64)
  needs //content/shell:thorium_shell(//build/toolchain/mac:clang_arm64)
```

I'm painfully unfamiliar with gn and pretty much everything surrounding the build process, so wondering if anyone can point me in the right direction. Thanks.

**Comment by Alex313031** [comment]
@wscullen This was an issue with the BUILD.gn script in the root of the repo and setup.sh not copying it over the chromium tree. It has been resolved.

**Comment by zakstal** [comment]
@wscullen Were you able to overcome this issue? I'm running into the same issue and have pulled a fresh repo in the last week.

**Comment by wscullen** [comment]
Unfortunately not. I got a little further by altering the build.gn in the required places to replace thorium_shell with content_shell, and only building the chrome target, but towards the end of the compile process I got a message about an undefined symbol.

Running:
`<path to depot_tools>/depot_tools/ninja -C <my user home dir>/chromium/src/out/thorium chrome  -j 8 -d stats`

Errors:
```
[1/165] LINK ./v8_context_snapshot_generator
FAILED: v8_context_snapshot_generator v8_context_snapshot_generator.dSYM/Contents/Info.plist v8_context_snapshot_generator.dSYM/Contents/Resources/DWARF/v8_context_snapshot_generator
TOOL_VERSION=1654625801 ../../build/toolchain/apple/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -Wcrl,installnametoolpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool ../../third_party/llvm-build/Release+Asserts/bin/clang++  -Wcrl,dsym,. -Wcrl,dsymutilpath,../../tools/clang/dsymutil/bin/dsymutil  -Werror -fuse-ld=lld -Wl,-fatal_warnings -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,-cache_path_lto,thinlto-cache -Wcrl,object_path_lto -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,-O3 -arch arm64 -no-canonical-prefixes -Wl,-mllvm,-extra-vectorizer-passes -Wl,-mllvm,-enable-cond-stores-vec -Wl,-mllvm,-slp-vectorize-hor-store -Wl,-mllvm,-enable-loopinterchange -Wl,-mllvm,-enable-loop-distribute -Wl,-mllvm,-enable-unroll-and-jam -Wl,-mllvm,-enable-loop-flatten -Wl,-mllvm,-interleave-small-loop-scalar-reduction -Wl,-mllvm,-unroll-runtime-multi-exit -Wl,-mllvm,-aggressive-ext-opt -Wl,-dead_strip -Wl,-no_data_in_code_info -Wl,-no_function_starts -nostdlib++ -isysroot ../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.13 -Wl,--lto-O3 -Wl,-ObjC -Wl,-O3 -Wcrl,strip,-x,-S -Wl,-O3 -Wl,--icf=none -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib -o "./v8_context_snapshot_generator" "@./v8_context_snapshot_generator.rsp"
ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtNextBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtNextBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltinWithResult
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltinWithResult
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltin
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltin
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltinWithResult
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltinWithResult
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltin
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltin
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _construct_stub_create_deopt_addr
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _construct_stub_create_deopt_addr
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _construct_stub_invoke_deopt_addr
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _construct_stub_invoke_deopt_addr
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtNextBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtNextBytecode
>>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o

ld64.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/apple/linker_driver.py", line 356, in <module>
    LinkerDriver(sys.argv).run()
  File "../../build/toolchain/apple/linker_driver.py", line 140, in run
    subprocess.check_call(compiler_driver_args, env=env)
  File ".pyenv/versions/3.8.13/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

Not sure how to solve this new issue, would be great if the person who helped with the M1 build on thorium could put together a step by step guide for people like me with less knowledge.

**Comment by gz83** [comment]
> Unfortunately not. I got a little further by altering the build.gn in the required places to replace thorium_shell with content_shell, and only building the chrome target, but towards the end of the compile process I got a message about an undefined symbol.
> 
> Running: `<path to depot_tools>/depot_tools/ninja -C <my user home dir>/chromium/src/out/thorium chrome -j 8 -d stats`
> 
> Errors:
> 
> ```
> [1/165] LINK ./v8_context_snapshot_generator
> FAILED: v8_context_snapshot_generator v8_context_snapshot_generator.dSYM/Contents/Info.plist v8_context_snapshot_generator.dSYM/Contents/Resources/DWARF/v8_context_snapshot_generator
> TOOL_VERSION=1654625801 ../../build/toolchain/apple/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -Wcrl,installnametoolpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool ../../third_party/llvm-build/Release+Asserts/bin/clang++  -Wcrl,dsym,. -Wcrl,dsymutilpath,../../tools/clang/dsymutil/bin/dsymutil  -Werror -fuse-ld=lld -Wl,-fatal_warnings -Wl,--icf=all -Wl,--color-diagnostics -Wl,-mllvm,-instcombine-lower-dbg-declare=0 -flto=thin -Wl,--thinlto-jobs=all -Wl,-cache_path_lto,thinlto-cache -Wcrl,object_path_lto -Wl,-mllvm,-import-instr-limit=30 -fwhole-program-vtables -Wl,-O3 -arch arm64 -no-canonical-prefixes -Wl,-mllvm,-extra-vectorizer-passes -Wl,-mllvm,-enable-cond-stores-vec -Wl,-mllvm,-slp-vectorize-hor-store -Wl,-mllvm,-enable-loopinterchange -Wl,-mllvm,-enable-loop-distribute -Wl,-mllvm,-enable-unroll-and-jam -Wl,-mllvm,-enable-loop-flatten -Wl,-mllvm,-interleave-small-loop-scalar-reduction -Wl,-mllvm,-unroll-runtime-multi-exit -Wl,-mllvm,-aggressive-ext-opt -Wl,-dead_strip -Wl,-no_data_in_code_info -Wl,-no_function_starts -nostdlib++ -isysroot ../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.13 -Wl,--lto-O3 -Wl,-ObjC -Wl,-O3 -Wcrl,strip,-x,-S -Wl,-O3 -Wl,--icf=none -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib -o "./v8_context_snapshot_generator" "@./v8_context_snapshot_generator.rsp"
> ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtNextBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtNextBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_InterpreterEnterAtBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltinWithResult
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltinWithResult
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltin
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToCodeStubBuiltin
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltinWithResult
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltinWithResult
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltin
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_ContinueToJavaScriptBuiltin
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _construct_stub_create_deopt_addr
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _construct_stub_create_deopt_addr
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _construct_stub_invoke_deopt_addr
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _construct_stub_invoke_deopt_addr
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtNextBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: undefined symbol: _Builtins_BaselineOrInterpreterEnterAtNextBytecode
> >>> referenced by obj/v8/v8_snapshot/deoptimizer-cfi-builtins.o
> 
> ld64.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> Traceback (most recent call last):
>   File "../../build/toolchain/apple/linker_driver.py", line 356, in <module>
>     LinkerDriver(sys.argv).run()
>   File "../../build/toolchain/apple/linker_driver.py", line 140, in run
>     subprocess.check_call(compiler_driver_args, env=env)
>   File ".pyenv/versions/3.8.13/lib/python3.8/subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> ```
> 
> Not sure how to solve this new issue, would be great if the person who helped with the M1 build on thorium could put together a step by step guide for people like me with less knowledge.

@wscullen @zakstal Do you need to compile for M1 Mac Thorium?

**Comment by wscullen** [comment]
Yep trying to build Thorium for M1 on my M1 mac.

**Comment by gz83** [comment]
> Yep trying to build Thorium for M1 on my M1 mac.

@wscullen Alex just updated the Thorium repository, you try to synchronize the latest update, and run setup_mac.sh to copy the newly modified files to $HOME/chromium/src/, and then run the compilation.

**Comment by wscullen** [comment]
Awesome, I'll give it a try tonight and report back, thanks!

**Comment by midzer** [comment]
@wscullen And don't forget to use https://github.com/Alex313031/Thorium-Special/blob/main/MAC_ARM_ARGS.gn instead of the one from regular Thorium.

**Comment by Alex313031** [comment]
@midzer @gz83 Thanks for answering. The previous errors were because the BUILD.gn in the root of the thorium repo were being copied, but this only needs to be done for windows and linux. The new setup_mac.sh should be used on Mac instead of setup.sh like for other platforms. There is also a new build_mac.sh to build it, and of course the same build_dmg.sh which you should run at the very end if you want an installation package. While build_dmg.sh does sign the binary, it is using the generic chromium signing key, and to install the .dmg you will have to tell it to allow the install even though it doesn't come from a known/trusted publisher.

**Comment by wscullen** [comment]
Ok it took a lot of trial and error and some major patience but I finally built Thorium on my M1 Macbook Pro:
<img width="949" alt="Screen Shot 2022-06-19 at 8 11 38 PM" src="https://user-images.githubusercontent.com/25625651/174513287-9784a5c8-25e5-4d52-a5a5-c8ee8cde9382.png">

Nothing was working with the custom Thorium files, so I tried to figure out how to build normal Chromium first. A big part of the puzzle was figuring out how to checkout the version of chromium I wanted to build and making sure all sub-repo dependencies were updated to match the version of chromium I was building. This link helped me with [helped me figure out how to checkout the version of chromium I wanted to build](https://stackoverflow.com/questions/47087970/how-to-checkout-and-build-specific-chromium-tag-branch-without-download-the-full) and I used [this page to find the version of chromium I wanted to build](https://chromiumdash.appspot.com/releases?platform=Mac). I was able to use the build args from the Thorium-Special repo, but I didn't run `setup_mac.sh`, I did use `build_mac.sh 8` as the build command and that worked, and a Chromium.app was built successfully.

Once that was working it was time to try the Thorium build again. I applied the same logic to find the version number, except this time I pulled the version number from the tags in the Thorium repo, in this case `M105.0.5127.0`. So I checkout that tag in Thorium repo and then used the same process from above to get the tag in the chromium repo. These are the steps I followed after making sure both repos where at the tag checkouts I wanted:

1) run `setup_mac.sh` in thorium repo
2) run the python command to download the latest profile file for mac and get the path for the profile file (from the `trunk.sh` file, I wasn't having luck with that script, it would stop at the git rebase-update command) in the chromium repo
`python3 tools/update_pgo_profiles.py --target=mac update --gs-url-base=chromium-optimization-profiles/pgo_profiles`
3) run `gn args out/thorium` from chromium repo and modify the `pgo_data_path` with the path from step 2, also paste in the build args from the Thorium-Special repo (MAC_ARM_ARGS.gn).
4) If 3 runs without problem, you can run `build_mac.sh 8` (8 is the number of processes, set that to the number of cores your cpu has).

During step 4 compile, you may run into issues, here's the 3 fixes I had to apply to the chromium source code that was modified by the Thorium setup script.

1) `./../chrome/browser/ui/views/translate/partial_translate_bubble_view.cc:504:11: error: use of undeclared identifier 'IDS_PARTIAL_TRANSLATE_BUBBLE_TRANSLATE_FULL_PAGE'`

Fix: Put the following back in at lines 10193 and 10253 in the file `src/chrome/app/generated_resources.grd`:
```
<message name="IDS_PARTIAL_TRANSLATE_BUBBLE_TRANSLATE_FULL_PAGE" desc="Text to show for the partial translate bubble button to start a full page translation">
            Translate Full Page
</message>
```

2) `../../chrome/browser/ui/ui_features.cc:147:21: error: unused variable 'kScrollableTabStripButtons' [-Werror,-Wunused-const-variable]`

Fix: Comment the following code at line 244 in file `src/chrome/browser/ui/ui_features.cc`:
```
// // Enables buttons to permanently appear on the tabstrip when
// // scrollable-tabstrip is enabled. https://crbug.com/1116118
// const base::Feature kScrollableTabStripButtons{
//     "ScrollableTabStripButtons", base::FEATURE_DISABLED_BY_DEFAULT};
```

3) `ld64.lld: error: undefined symbol: blink::features::kTimedHTMLParserBudget
>>> referenced by thinlto-cache/llvmcache-4BA72871AEA93858C7F76863FE4DE06092D96A7F:(symbol __ZN5blink18HTMLDocumentParserC2ERNS_8DocumentENS_19ParserContentPolicyENS_27ParserSynchronizationPolicyENS_20ParserPrefetchPolicyE+0x3fc)`

Fix: Add the following to line 1546 in file `src/third_party/blink/common/features.cc`:
```
const base::Feature kTimedHTMLParserBudget{"TimedHTMLParserBudget",
                                           base::FEATURE_DISABLED_BY_DEFAULT};
```

After those fixes the build process should complete successfully. To build the dmg for the app, either move the `build_dmg.sh` to the chromium repo and run it from there, or add `cd /Users/<user_account>/chromium/src &&` to the `build_dmg.sh` script and run from the Thorium repo.

Many many MANY thanks to @Alex313031 and @midzer  for their hard work in making this work. Hope this helps someone else spending way too much time on this like me!

**Comment by gz83** [comment]
> Ok it took a lot of trial and error and some major patience but I finally built Thorium on my M1 Macbook Pro: <img alt="Screen Shot 2022-06-19 at 8 11 38 PM" width="949" src="https://user-images.githubusercontent.com/25625651/174513287-9784a5c8-25e5-4d52-a5a5-c8ee8cde9382.png">
> 
> Nothing was working with the custom Thorium files, so I tried to figure out how to build normal Chromium first. A big part of the puzzle was figuring out how to checkout the version of chromium I wanted to build and making sure all sub-repo dependencies were updated to match the version of chromium I was building. This link [helped me figure out how to checkout the version of chromium I wanted to build](https://stackoverflow.com/questions/47087970/how-to-checkout-and-build-specific-chromium-tag-branch-without-download-the-full) and I used [this page to find the version of chromium I wanted to build](https://chromiumdash.appspot.com/releases?platform=Mac). I was able to use the build args from the Thorium-Special repo, but I didn't run `setup_mac.sh`, I did use `build_mac.sh 8` as the build command and that worked, and a Chromium.app was built successfully.
> 
> Once that was working it was time to try the Thorium build again. I applied the same logic to find the version number, except this time I pulled the version number from the tags in the Thorium repo, in this case `M105.0.5127.0`. So I checkout that tag in Thorium repo and then used the same process from above to get the tag in the chromium repo. These are the steps I followed after making sure both repos were at the tag checkouts I wanted:
> 
> 1. run `setup_mac.sh` in thorium repo
> 2. run the python command to download the latest profile file for mac and get the path for the profile file (from the `trunk.sh` file, I wasn't having luck with that script, it would stop at the git rebase-update command) in the chromium repo
>    `python3 tools/update_pgo_profiles.py --target=mac update --gs-url-base=chromium-optimization-profiles/pgo_profiles`
> 3. run `gn args out/thorium` from chromium repo and modify the `pgo_data_path` with the path from step 2, also paste in the build args from the Thorium-Special repo (MAC_ARM_ARGS.gn).
> 4. If  step 3 runs without problem, you can run `build_mac.sh 8` (8 is the number of processes, set that to the number of cores your cpu has).
> 
> During step 4 compile, you may run into issues, here's the 3 fixes I had to apply to the chromium source code that was modified by the Thorium setup script.
> 
> 1. `./../chrome/browser/ui/views/translate/partial_translate_bubble_view.cc:504:11: error: use of undeclared identifier 'IDS_PARTIAL_TRANSLATE_BUBBLE_TRANSLATE_FULL_PAGE'`
> 
> Fix: Put the following back in at lines 10193 and 10253 in the file `src/chrome/app/generated_resources.grd`:
> 
> ```
> <message name="IDS_PARTIAL_TRANSLATE_BUBBLE_TRANSLATE_FULL_PAGE" desc="Text to show for the partial translate bubble button to start a full page translation">
>             Translate Full Page
> </message>
> ```
> 
> 2. `../../chrome/browser/ui/ui_features.cc:147:21: error: unused variable 'kScrollableTabStripButtons' [-Werror,-Wunused-const-variable]`
> 
> Fix: Comment the following code at line 244 in file `src/chrome/browser/ui/ui_features.cc`:
> 
> ```
> // // Enables buttons to permanently appear on the tabstrip when
> // // scrollable-tabstrip is enabled. https://crbug.com/1116118
> // const base::Feature kScrollableTabStripButtons{
> //     "ScrollableTabStripButtons", base::FEATURE_DISABLED_BY_DEFAULT};
> ```
> 
> 3. `ld64.lld: error: undefined symbol: blink::features::kTimedHTMLParserBudget
> 
> > > > referenced by thinlto-cache/llvmcache-4BA72871AEA93858C7F76863FE4DE06092D96A7F:(symbol __ZN5blink18HTMLDocumentParserC2ERNS_8DocumentENS_19ParserContentPolicyENS_27ParserSynchronizationPolicyENS_20ParserPrefetchPolicyE+0x3fc)`
> 
> Fix: Add the following to line 1546 in file `src/third_party/blink/common/features.cc`:
> 
> ```
> const base::Feature kTimedHTMLParserBudget{"TimedHTMLParserBudget",
>                                            base::FEATURE_DISABLED_BY_DEFAULT};
> ```
> 
> After those fixes the build process should complete successfully. To build the dmg for the app, either move the `build_dmg.sh` to the chromium repo and run it from there, or add `cd /Users/<user_account>/chromium/src &&` to the `build_dmg.sh` script and run from the Thorium repo.
> 
> Many many MANY thanks to @Alex313031 and @midzer for their hard work in making this work. Hope this helps someone else spending way too much time on this like me! Also, for troubleshooting problems that happen during compile, it helps to open the chromium repo in a IDE so you can see what files were modified by the `setup_mac.sh` file, this helped me a lot to find which files I needed to edit to let the build finish successfully.
> 
> PS. New icon looking good! <img alt="Screen Shot 2022-06-19 at 8 56 10 PM" width="67" src="https://user-images.githubusercontent.com/25625651/174517275-7c51c092-53ad-470c-998f-2c1d647ddfcf.png">

@wscullen Very happy to see that you successfully compiled Thorium.

If you encounter the problem that the `git rebase-update` command cannot be executed, you can enter the chromium/src directory, execute `git status` to check the status of git, and then process the conflicting files. After processing, `trunk.sh` It should work fine.

If there are errors such as linker errors and undefined symbols during compilation, it is recommended to execute the `git pull origin main` command in the Thorium directory to pull the latest modifications of the Thorium repository, and run `setup_mac.sh` to copy the Thorium files to Chromium/src, then go back to the Thorium directory and run `build_mac.sh` to compile, you can set the value of `-j` to the number of CPU threads when compiling.

Errors may also occur during the execution of the `git pull origin main` command. If an error occurs, you also need to manually resolve the conflicting files.

**Comment by gz83** [comment]
> Ok it took a lot of trial and error and some major patience but I finally built Thorium on my M1 Macbook Pro: <img alt="Screen Shot 2022-06-19 at 8 11 38 PM" width="949" src="https://user-images.githubusercontent.com/25625651/174513287-9784a5c8-25e5-4d52-a5a5-c8ee8cde9382.png">
> 
> Nothing was working with the custom Thorium files, so I tried to figure out how to build normal Chromium first. A big part of the puzzle was figuring out how to checkout the version of chromium I wanted to build and making sure all sub-repo dependencies were updated to match the version of chromium I was building. This link [helped me figure out how to checkout the version of chromium I wanted to build](https://stackoverflow.com/questions/47087970/how-to-checkout-and-build-specific-chromium-tag-branch-without-download-the-full) and I used [this page to find the version of chromium I wanted to build](https://chromiumdash.appspot.com/releases?platform=Mac). I was able to use the build args from the Thorium-Special repo, but I didn't run `setup_mac.sh`, I did use `build_mac.sh 8` as the build command and that worked, and a Chromium.app was built successfully.
> 
> Once that was working it was time to try the Thorium build again. I applied the same logic to find the version number, except this time I pulled the version number from the tags in the Thorium repo, in this case `M105.0.5127.0`. So I checkout that tag in Thorium repo and then used the same process from above to get the tag in the chromium repo. These are the steps I followed after making sure both repos were at the tag checkouts I wanted:
> 
> 1. run `setup_mac.sh` in thorium repo
> 2. run the python command to download the latest profile file for mac and get the path for the profile file (from the `trunk.sh` file, I wasn't having luck with that script, it would stop at the git rebase-update command) in the chromium repo
>    `python3 tools/update_pgo_profiles.py --target=mac update --gs-url-base=chromium-optimization-profiles/pgo_profiles`
> 3. run `gn args out/thorium` from chromium repo and modify the `pgo_data_path` with the path from step 2, also paste in the build args from the Thorium-Special repo (MAC_ARM_ARGS.gn).
> 4. If  step 3 runs without problem, you can run `build_mac.sh 8` (8 is the number of processes, set that to the number of cores your cpu has).
> 
> During step 4 compile, you may run into issues, here's the 3 fixes I had to apply to the chromium source code that was modified by the Thorium setup script.
> 
> 1. `./../chrome/browser/ui/views/translate/partial_translate_bubble_view.cc:504:11: error: use of undeclared identifier 'IDS_PARTIAL_TRANSLATE_BUBBLE_TRANSLATE_FULL_PAGE'`
> 
> Fix: Put the following back in at lines 10193 and 10253 in the file `src/chrome/app/generated_resources.grd`:
> 
> ```
> <message name="IDS_PARTIAL_TRANSLATE_BUBBLE_TRANSLATE_FULL_PAGE" desc="Text to show for the partial translate bubble button to start a full page translation">
>             Translate Full Page
> </message>
> ```
> 
> 2. `../../chrome/browser/ui/ui_features.cc:147:21: error: unused variable 'kScrollableTabStripButtons' [-Werror,-Wunused-const-variable]`
> 
> Fix: Comment the following code at line 244 in file `src/chrome/browser/ui/ui_features.cc`:
> 
> ```
> // // Enables buttons to permanently appear on the tabstrip when
> // // scrollable-tabstrip is enabled. https://crbug.com/1116118
> // const base::Feature kScrollableTabStripButtons{
> //     "ScrollableTabStripButtons", base::FEATURE_DISABLED_BY_DEFAULT};
> ```
> 
> 3. `ld64.lld: error: undefined symbol: blink::features::kTimedHTMLParserBudget
> 
> > > > referenced by thinlto-cache/llvmcache-4BA72871AEA93858C7F76863FE4DE06092D96A7F:(symbol __ZN5blink18HTMLDocumentParserC2ERNS_8DocumentENS_19ParserContentPolicyENS_27ParserSynchronizationPolicyENS_20ParserPrefetchPolicyE+0x3fc)`
> 
> Fix: Add the following to line 1546 in file `src/third_party/blink/common/features.cc`:
> 
> ```
> const base::Feature kTimedHTMLParserBudget{"TimedHTMLParserBudget",
>                                            base::FEATURE_DISABLED_BY_DEFAULT};
> ```
> 
> After those fixes the build process should complete successfully. To build the dmg for the app, either move the `build_dmg.sh` to the chromium repo and run it from there, or add `cd /Users/<user_account>/chromium/src &&` to the `build_dmg.sh` script and run from the Thorium repo.
> 
> Many many MANY thanks to @Alex313031 and @midzer for their hard work in making this work. Hope this helps someone else spending way too much time on this like me! Also, for troubleshooting problems that happen during compile, it helps to open the chromium repo in a IDE so you can see what files were modified by the `setup_mac.sh` file, this helped me a lot to find which files I needed to edit to let the build finish successfully.
> 
> PS. New icon looking good! <img alt="Screen Shot 2022-06-19 at 8 56 10 PM" width="67" src="https://user-images.githubusercontent.com/25625651/174517275-7c51c092-53ad-470c-998f-2c1d647ddfcf.png">

@wscullen Very happy to see that you successfully compiled Thorium.

If you encounter the problem that the `git rebase-update` command cannot be executed, you can enter the chromium/src directory, execute `git status` to check the status of git, and then process the conflicting files. After processing, `trunk.sh` It should work fine.

If there are errors such as linker errors and undefined symbols during compilation, it is recommended to execute the `git pull origin main` command in the Thorium directory to pull the latest modifications of the Thorium repository, and run `setup_mac.sh` to copy the Thorium files to Chromium/src, then go back to the Thorium directory and run `build_mac.sh` to compile, you can set the value of `-j` to the number of CPU threads when compiling.

Errors may also occur during the execution of the `git pull origin main` command. If an error occurs, you also need to manually resolve the conflicting files.

**Comment by zakstal** [comment]
Thanks!
